<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Crear Post</h1>
    <form action="index.php?c=post" method="POST">
        <input type="text" name="title" placeholder="Titulo">
        <input type="text" name="content" placeholder="Contenido">
        <input type="submit" value="Crear Post">
    </form>
    <a href="index.php">Volver</a>
</body>

</html>