<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a href="index.php?c=user&logout=1">Logout</a>

    <?php foreach ($posts as $post) {
        if ($post->getVisible()) {
            echo '<a href="index.php?c=post&id=' . $post->getId() . '"><h2>' . $post->getTitle() . '</h2></a>';
        };
    }
    ?>
</body>

</html>